services:
  sales_db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: sales  # database chính sẽ là sales
    volumes:
      - sales_db:/var/lib/postgresql/data/
#      - ./init-multiple-db.sh:/docker-entrypoint-initdb.d/init-multiple-db.sh
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d sales"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  sales_db:
